services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "50505:50505"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  db:
    image: postgres:latest
    environment:
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBNAME: ${DBNAME}
      DBPORT: ${DBPORT}
    ports:
      - "${DBPORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
